version: '3.8'

services: 
  discord:
    container_name: discord_bot
    #image: python:alpine
    restart: always

    build: 
      context: .
      dockerfile: ./Dockerfile

    volumes: 
      - ./music:/tmp/discordbot/
      - ./src:/app/
