version: '3.8'

services: 
  discord:
    container_name: discord_bot
    restart: always
    dns: 1.1.1.1

    build: 
      context: .
      dockerfile: ./docker/Dockerfile.local

    volumes: 
      - ./music:/tmp/discordbot/
      - ./src:/app/

    command: python /app/main.py

    environment:
      TZ: Asia/Tokyo