version: '3.8'

services: 
  discord:
    container_name: discord_bot
    restart: always
    dns: 1.1.1.1

    build: 
      context: .
      dockerfile: ./Dockerfile.local

    volumes: 
      - ./music:/tmp/discordbot/
      - .:/app/

    command: python /app/src/main.py

    environment:
      TZ: Asia/Tokyo